<?php

namespace Database\Factories;

use App\Models\ChargingStation;
use App\Models\Organization;
use App\Models\User;
use App\Models\Vehicle;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\ChargingSession>
 */
class ChargingSessionFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $statuses = ['in_progress', 'completed', 'interrupted', 'failed'];
        $paymentMethods = ['credit_card', 'fleet_card', 'mobile_app', 'subscription', 'free'];
        $paymentStatuses = ['pending', 'completed', 'failed', 'refunded'];

        $batteryStart = $this->faker->numberBetween(10, 50);
        $batteryEnd = $this->faker->numberBetween($batteryStart + 20, 100);
        $energyDelivered = $this->faker->randomFloat(2, 10, 80);
        $costPerKwh = $this->faker->randomFloat(4, 0.10, 0.50);
        $durationMinutes = $this->faker->numberBetween(15, 180);
        $startTime = $this->faker->dateTimeBetween('-3 months', 'now');

        return [
            'organization_id' => Organization::factory(),
            'vehicle_id' => Vehicle::factory(),
            'charging_station_id' => ChargingStation::factory(),
            'driver_id' => User::factory(),

            'session_number' => null, // Will be auto-generated by model
            'status' => $this->faker->randomElement($statuses),

            // Battery levels
            'battery_level_start_percent' => $batteryStart,
            'battery_level_end_percent' => $batteryEnd,

            // Session timing
            'start_time' => $startTime,
            'end_time' => (clone $startTime)->modify("+{$durationMinutes} minutes"),
            'duration_minutes' => $durationMinutes,

            // Energy and cost
            'energy_delivered_kwh' => $energyDelivered,
            'cost_per_kwh' => $costPerKwh,
            'cost_per_minute' => $this->faker->randomFloat(4, 0.01, 0.10),
            'idle_time_minutes' => $this->faker->numberBetween(0, 30),
            'idle_fee' => $this->faker->randomFloat(2, 0, 10),
            'total_cost' => $energyDelivered * $costPerKwh,
            'currency' => 'EUR',

            // Charging details
            'charging_power_kw' => $this->faker->randomElement([7, 11, 22, 50, 150]),
            'peak_power_kw' => $this->faker->randomFloat(2, 20, 200),
            'average_power_kw' => $this->faker->randomFloat(2, 10, 100),
            'connector_used' => $this->faker->randomElement(['Type 2', 'CCS', 'CHAdeMO']),

            // Payment and transaction
            'payment_method' => $this->faker->randomElement($paymentMethods),
            'payment_status' => $this->faker->randomElement($paymentStatuses),
            'transaction_id' => $this->faker->uuid(),
            'invoice_number' => $this->faker->boolean(70) ? 'INV-' . $this->faker->numerify('######') : null,

            // Environmental impact
            'co2_saved_kg' => $this->faker->randomFloat(2, 1, 50),

            // Session quality
            'interruption_count' => $this->faker->numberBetween(0, 3),
            'error_codes' => $this->faker->boolean(10) ? $this->faker->word() : null,

            // Location at start
            'start_latitude' => $this->faker->latitude(),
            'start_longitude' => $this->faker->longitude(),

            // Additional information
            'notes' => $this->faker->boolean(20) ? $this->faker->sentence() : null,
        ];
    }

    /**
     * Indicate that the session is completed.
     */
    public function completed(): static
    {
        return $this->state(function (array $attributes) {
            $durationMinutes = $this->faker->numberBetween(30, 180);
            $startTime = $this->faker->dateTimeBetween('-3 months', '-1 day');
            $energyDelivered = $this->faker->randomFloat(2, 20, 80);
            $costPerKwh = $attributes['cost_per_kwh'] ?? 0.25;

            return [
                'status' => 'completed',
                'battery_level_end_percent' => $this->faker->numberBetween(70, 100),
                'start_time' => $startTime,
                'end_time' => (clone $startTime)->modify("+{$durationMinutes} minutes"),
                'duration_minutes' => $durationMinutes,
                'energy_delivered_kwh' => $energyDelivered,
                'total_cost' => $energyDelivered * $costPerKwh,
                'payment_status' => 'completed',
            ];
        });
    }

    /**
     * Indicate that the session is in progress.
     */
    public function inProgress(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => 'in_progress',
            'battery_level_end_percent' => null,
            'end_time' => null,
            'duration_minutes' => null,
            'energy_delivered_kwh' => null,
            'total_cost' => null,
            'payment_status' => 'pending',
            'start_time' => $this->faker->dateTimeBetween('-2 hours', 'now'),
        ]);
    }

    /**
     * Indicate that the session was interrupted.
     */
    public function interrupted(): static
    {
        return $this->state(function (array $attributes) {
            $durationMinutes = $this->faker->numberBetween(5, 60);
            $startTime = $this->faker->dateTimeBetween('-1 week', '-1 day');
            $energyDelivered = $this->faker->randomFloat(2, 1, 20);
            $costPerKwh = $attributes['cost_per_kwh'] ?? 0.25;

            return [
                'status' => 'interrupted',
                'battery_level_end_percent' => $this->faker->numberBetween(30, 70),
                'start_time' => $startTime,
                'end_time' => (clone $startTime)->modify("+{$durationMinutes} minutes"),
                'duration_minutes' => $durationMinutes,
                'energy_delivered_kwh' => $energyDelivered,
                'total_cost' => $energyDelivered * $costPerKwh,
                'interruption_count' => $this->faker->numberBetween(1, 5),
                'error_codes' => $this->faker->randomElement(['ERR_001', 'ERR_TIMEOUT', 'ERR_CONNECTION']),
            ];
        });
    }

    /**
     * Indicate that the session is a fast charging session.
     */
    public function fastCharging(): static
    {
        return $this->state(function (array $attributes) {
            $durationMinutes = $this->faker->numberBetween(15, 45);
            $energyDelivered = $this->faker->randomFloat(2, 30, 80);
            $costPerKwh = $attributes['cost_per_kwh'] ?? 0.40;

            return [
                'charging_power_kw' => $this->faker->randomElement([50, 150, 350]),
                'peak_power_kw' => $this->faker->randomFloat(2, 100, 350),
                'average_power_kw' => $this->faker->randomFloat(2, 80, 200),
                'connector_used' => $this->faker->randomElement(['CCS', 'CHAdeMO']),
                'duration_minutes' => $durationMinutes,
                'energy_delivered_kwh' => $energyDelivered,
                'total_cost' => $energyDelivered * $costPerKwh,
            ];
        });
    }
}
