<?php

namespace Database\Factories;

use App\Models\Organization;
use App\Models\Site;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\ChargingStation>
 */
class ChargingStationFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $types = ['home', 'workplace', 'public', 'private', 'depot'];
        $connectorTypes = ['Type 2', 'CCS', 'CHAdeMO', 'Tesla Supercharger', 'Type 1', 'AC'];
        $statuses = ['available', 'occupied', 'maintenance', 'offline', 'reserved'];
        $accessTypes = ['public', 'private', 'semi-public'];

        return [
            'organization_id' => Organization::factory(),
            'site_id' => $this->faker->boolean(70) ? Site::factory() : null,
            'name' => $this->faker->randomElement([
                'Station ' . $this->faker->streetName,
                $this->faker->company . ' Charging Point',
                'Depot Charger ' . $this->faker->numberBetween(1, 100),
            ]),
            'station_code' => null, // Will be auto-generated by model
            'type' => $this->faker->randomElement($types),
            'connector_type' => $this->faker->randomElement($connectorTypes),
            'max_power_kw' => $this->faker->randomElement([7, 11, 22, 50, 150, 350]),
            'status' => $this->faker->randomElement($statuses),
            'is_active' => $this->faker->boolean(90),

            // Location
            'latitude' => $this->faker->latitude(),
            'longitude' => $this->faker->longitude(),
            'address' => $this->faker->streetAddress(),
            'city' => $this->faker->city(),
            'postal_code' => $this->faker->postcode(),
            'country' => $this->faker->country(),

            // Technical specifications
            'voltage_v' => $this->faker->randomElement([230, 400]),
            'amperage_a' => $this->faker->randomElement([16, 32, 63]),
            'number_of_connectors' => $this->faker->numberBetween(1, 4),
            'supports_smart_charging' => $this->faker->boolean(60),
            'supports_payment' => $this->faker->boolean(70),
            'network_provider' => $this->faker->randomElement(['ChargePoint', 'EVBox', 'Tesla', 'Ionity', 'Shell Recharge', null]),
            'station_protocol' => $this->faker->randomElement(['OCPP 1.6', 'OCPP 2.0', 'CHAdeMO', 'CCS', null]),

            // Pricing
            'cost_per_kwh' => $this->faker->randomFloat(4, 0.10, 0.50),
            'cost_per_minute' => $this->faker->randomFloat(4, 0.01, 0.10),
            'idle_fee_per_minute' => $this->faker->randomFloat(4, 0.05, 0.30),
            'currency' => 'EUR',

            // Access and restrictions
            'requires_authentication' => $this->faker->boolean(70),
            'access_type' => $this->faker->randomElement($accessTypes),
            'requires_membership' => $this->faker->boolean(30),
            'access_hours' => $this->faker->randomElement(['24/7', '06:00-22:00', '08:00-18:00', null]),
            'parking_restrictions' => $this->faker->boolean(30) ? $this->faker->sentence() : null,

            // Operational data
            'installation_date' => $this->faker->dateTimeBetween('-2 years', '-1 month'),
            'last_maintenance_date' => $this->faker->dateTimeBetween('-6 months', 'now'),
            'next_maintenance_date' => $this->faker->dateTimeBetween('now', '+6 months'),
            'warranty_expiry_date' => $this->faker->dateTimeBetween('+1 year', '+5 years'),

            // Manufacturer information
            'manufacturer' => $this->faker->randomElement(['ABB', 'Schneider Electric', 'Siemens', 'Tesla', 'EVBox', 'ChargePoint']),
            'model' => $this->faker->bothify('Model-##??'),
            'serial_number' => $this->faker->bothify('SN-########'),
            'firmware_version' => $this->faker->numerify('#.#.#'),

            // Usage statistics (will be updated by sessions)
            'total_sessions' => 0,
            'total_energy_delivered_kwh' => 0,
            'total_revenue' => 0,
            'average_session_duration_minutes' => 0,
            'utilization_rate_percent' => 0,
            'last_session_date' => null,

            // Additional fields
            'notes' => $this->faker->boolean(20) ? $this->faker->sentence() : null,
            'qr_code' => $this->faker->boolean(50) ? $this->faker->uuid() : null,
            'image_url' => $this->faker->boolean(30) ? $this->faker->imageUrl() : null,
        ];
    }

    /**
     * Indicate that the station is a depot station.
     */
    public function depot(): static
    {
        return $this->state(fn (array $attributes) => [
            'type' => 'depot',
            'access_type' => 'private',
            'requires_authentication' => true,
            'max_power_kw' => $this->faker->randomElement([22, 50]),
        ]);
    }

    /**
     * Indicate that the station is a public fast charger.
     */
    public function publicFastCharger(): static
    {
        return $this->state(fn (array $attributes) => [
            'type' => 'public',
            'access_type' => 'public',
            'connector_type' => $this->faker->randomElement(['CCS', 'CHAdeMO']),
            'max_power_kw' => $this->faker->randomElement([50, 150, 350]),
            'access_hours' => '24/7',
        ]);
    }

    /**
     * Indicate that the station is unavailable.
     */
    public function unavailable(): static
    {
        return $this->state(fn (array $attributes) => [
            'status' => $this->faker->randomElement(['maintenance', 'offline']),
            'is_active' => false,
        ]);
    }
}
